### ISSUE TITLE
Build website is broken

### ISSUE THREAD

**Issue by AmiZya** [i3/build.i3wm.org#1]
Hello,

Happened this morning, the build website is broken and causes the Debian repository to throw 404 error.

Logs:

> W: The repository 'http://build.i3wm.org/debian/sid sid Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://build.i3wm.org/debian/sid/dists/sid/main/binary-i386/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by stapelberg** [comment]
This is intentional, please see https://www.freelists.org/post/i3-announce/autobuilt-packages-migration-please-change-your-sourceslist
